# To create a release:
# git tag v1.0.0
# git push origin v1.0.0
# or
# use Github UI -> Create Release -> Create New Tag -> v1.0.0 -> Publish Release

name: Create release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.2
      with:
        fetch-depth: 0 # Fetch all history for all tags
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 9.x
    - name: create-release-notes
      id: notes
      # You may pin to the exact commit or the version.
      # uses: johnyherangi/create-release-notes@8986cd6f5959f917ca328b0fe0849e1cab7f5920
      uses: johnyherangi/create-release-notes@v1
      #with:
        # Custom head ref
        #head-ref: # optional, default is HEAD
        # Release note format
        #format: # optional, default is - {{subject}} by @{{author}}
    - name: Install dependencies
      run: dotnet restore -p:SelfContained=true
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Dotnet Tests
      uses: EasyDesk/action-dotnet-test@v1.3.0
      with:
        skip-build: true # optional, default is true
    - name: Publish
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore  -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExe.pubxml
    - name: Publish
      run: dotnet publish GlucoseTray\GlucoseTray.csproj --configuration Release --no-restore  -p:PublishProfile=GlucoseTray\Properties\PublishProfiles\PublishToSingleSelfContainedExeWthoutFramework.pubxml
    - name: Create a new release note
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        name: GlucoseTray ${{ github.ref_name }}
        body: |
          ${{ steps.notes.outputs.release-notes }}
        draft: false
        prerelease: false
        append_body: true
        fail_on_unmatched_files: true
        generate_release_notes: false # !important
        files: |
          ./GlucoseTray/bin/Release/net9.0-windows7.0/publish/win-x64/GlucoseTray.exe
          ./GlucoseTray/bin/Release/net9.0-windows7.0/publish/win-x64-small/GlucoseTray-Slim.exe
          ./README.md
