# Action on pull requests : Build, but don't create a release

name: .NET Core Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0 # Fetch all history for all tags
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: 10.x
    - name: Install dependencies
      run: dotnet restore -p:SelfContained=true
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Dotnet Tests
      uses: EasyDesk/action-dotnet-test@v1.3.0
      with:
        skip-build: true # optional, default is true
    - name: Publish
      run: dotnet publish --configuration Release --no-restore
